### ISSUE TITLE
RangeError: 'length' is outside of buffer bounds when sending long messages

### ISSUE THREAD

**Issue by codebyDanielDev** [nizarfadlan/baileys-api#13]
---
RangeError: 'length' is outside of buffer bounds when sending long messages
---

**Description of the Problem:**

When trying to send a message I get the following error:
![image](https://github.com/user-attachments/assets/2f590adc-bc19-4cc9-a149-b1e4a8e122b6)

**Steps to Play:**

1. Add a session
2. Enviar el mensaje:
![image](https://github.com/user-attachments/assets/03e3a137-323b-471f-aeb2-a91b55d6a190)

**Expected Behavior:**

The message should be sent correctly and this is a somewhat long message.

**This way it works**
![image](https://github.com/user-attachments/assets/2a59c97c-a149-40da-8206-e11c3d71750d)

**Entorno:**

- Ubuntu 24

**Additional Comments:**

This problem in version 1 was not

---

**Comment by nizarfadlan** [comment]
If the screenshot given has a problem with protobufjs in baileys, but I tried a longer text than that there was no problem at all, but I checked in the baileys issue I found https://github.com/WhiskeySockets/Baileys/issues/1003. Can you inform me what version of NodeJS you are using? because I am using version 20

![WhatsApp Image 2024-09-11 at 12 18 51](https://github.com/user-attachments/assets/ca37e40f-f351-45db-b18e-461d0fb7691c)

**Comment by codebyDanielDev** [comment]
Hi, using node 22.7.0

I'll try to use it in one less version, send inforemes.

**Comment by codebyDanielDev** [comment]
@nizarfadlan Funciona correctamente hasta la cversion 21.7.3, para la version 22.7.0 da este error

**Comment by codebyDanielDev** [comment]
![image](https://github.com/user-attachments/assets/f9995894-cdf8-420d-881a-baad458a536e)

**Comment by nizarfadlan** [comment]
> @nizarfadlan Funciona correctamente hasta la cversion 21.7.3, para la version 22.7.0 da este error

Yes it is an error in node version 22.7.0, you can see the announcement on the official baileys channel 

You can see this https://discord.com/channels/725839806084546610/936242835244605451/1276571738280300597
